apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: sample-pipeline-run
  namespace: your-namespace
spec:
  pipelineRef:
    name: sample-pipeline
  params:
    - name: IMAGE
      value: "quay.io/your-image:latest"
  resources:
    - name: git-repo
      resourceRef:
        name: git-repo
