apiVersion: tekton.dev/v1
kind: Task
metadata:
  creationTimestamp: '2024-12-28T16:03:14Z'
  generation: 1
  managedFields:
    - apiVersion: tekton.dev/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:params': {}
          'f:steps': {}
      manager: kubectl-create
      operation: Update
      time: '2024-12-28T16:03:14Z'
  name: update-deployment
  namespace: pipelines-tutorial
  resourceVersion: '46060'
  uid: 15a9a965-67cb-4394-b8d9-2c534b6bacbb
spec:
  params:
    - description: The name of the deployment patch the image
      name: deployment
      type: string
    - description: Location of image to be patched with
      name: IMAGE
      type: string
  steps:
    - args:
        - |-
          oc patch deployment $(inputs.params.deployment) --patch='{"spec":{"template":{"spec":{
            "containers":[{
              "name": "$(inputs.params.deployment)",
              "image":"$(inputs.params.IMAGE)"
            }]
          }}}}'
      command:
        - /bin/bash
        - '-c'
      computeResources: {}
      image: 'quay.io/openshift/origin-cli:latest'
      name: patch
