name: Deploy to IBM Cloud Code Engine

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Log in to IBM Cloud
    - name: Log in to IBM Cloud
      run: |
        curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
        ibmcloud config --check-version=false
        ibmcloud login --apikey "${{ secrets.IBM_CLOUD_API_KEY }}" -r "${{ secrets.IBM_REGION }}"
    
    # install ibm dependencies
    - name: install ibm dependencies
      run: |
       ibmcloud plugin install container-registry
       ibmcloud plugin install code-engine


    # Log in to IBM Container Registry
    - name: Log in to IBM Container Registry
      run: |
        # ibmcloud cr login
        ibmcloud cr region-set us-south
        ibmcloud cr login --client docker
        ibmcloud cr namespace-add "${{ secrets.IBM_CR_NAMESPACE }}" || true

    # Build the container
    - name: Build and tag Docker image
      run: |
        docker build -t "us.icr.io/${{ secrets.IBM_CR_NAMESPACE }}/${{ secrets.IMAGE_NAME }}:latest" .
        # docker tag "us.icr.io/${{ secrets.IBM_CR_NAMESPACE }}/${{ secrets.IMAGE_NAME }}:latest" toursbackend:latest

      
    # Pull and push the official Redis image to ICR
    # If you prefer, you can skip pushing Redis to ICR and just reference the official image directly.
    # - name: Prepare Redis Image
    #   run: |
    #     docker pull redis:latest
    #     docker tag redis:latest us.icr.io/${{ secrets.IBM_CR_NAMESPACE }}/${{ secrets.IMAGE_NAME_2 }}:latest
    #     # docker push us.icr.io/my-namespace/redis:latest
    
    # Pull and push the official elastic image to ICR
    # - name: pull and tag elasticsearch and kibana image for code engine
    #   run: |
    #     docker pull docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    #     docker pull docker.elastic.co/kibana/kibana:8.17.0
    #     docker tag  docker.elastic.co/elasticsearch/elasticsearch:8.17.0 us.icr.io/${{ secrets.IBM_CR_NAMESPACE }}/elasticsearch:8.17.0
    #     docker tag  docker.elastic.co/kibana/kibana:8.17.0  us.icr.io/${{ secrets.IBM_CR_NAMESPACE }}/kibana:8.17.0

    #docker login to container registry
    - name: docker login to container registry
      run: |
         docker login -u iamapikey --password ${{ secrets.DOCKER_IAM }} icr.io

    # Push the node container to IBM Container Registry
    - name: Push node image to IBM Container Registry
      run: |
        docker push "us.icr.io/${{ secrets.IBM_CR_NAMESPACE }}/${{ secrets.IMAGE_NAME }}:latest"
        # docker push "us.icr.io/${{ secrets.IBM_CR_NAMESPACE }}/elasticsearch:8.17.0"
        # docker push "us.icr.io/${{ secrets.IBM_CR_NAMESPACE }}/kibana:8.17.0"

    # Push the redis container to IBM Container Registry
    # - name: Push redis image to IBM Container Registry
    #   run: |
    #     docker push "us.icr.io/${{ secrets.IBM_CR_NAMESPACE }}/${{ secrets.IMAGE_NAME_2 }}:latest"
          

    # inspect containers (optional)
    - name: Verify image in registry
      run: |
        ibmcloud cr image-inspect "us.icr.io/${{ secrets.IBM_CR_NAMESPACE }}/${{ secrets.IMAGE_NAME }}:latest"

    # Deploy to IBM Cloud Code Engine
    - name: Deploy to IBM Cloud Code Engine
      run: |
        ibmcloud target -c ${{ secrets.ACCOUNT_ID }} -r ${{ secrets.REGION_NAME }} -g Default
        ibmcloud ce project select --name ${{ secrets.CODE_ENGINE_PROJECT }} --quiet

        ibmcloud ce application update --name "tourstravelserver" --registry-secret my-us-reg-secret \
        --image "us.icr.io/${{ secrets.IBM_CR_NAMESPACE }}/${{ secrets.IMAGE_NAME }}:latest" \
        --port 4000 \
        --env REDIS_PASSWORD=${{secrets.REDIS_PASSWORD}} --env LOG_LEVEL=${{ secrets.LOG_LEVEL }} \
        --env ELASTIC_SEARCH_HOST={{ secrets.ELASTIC_SEARCH_HOST }}  || \
        ibmcloud ce application create --name "tourstravelserver" --registry-secret my-us-reg-secret \
        --image "us.icr.io/${{ secrets.IBM_CR_NAMESPACE }}/${{ secrets.IMAGE_NAME }}:latest" \
        --port 4000 \
        --env REDIS_PASSWORD=${{secrets.REDIS_PASSWORD}} --env LOG_LEVEL=${{ secrets.LOG_LEVEL }} \
        --env ELASTIC_SEARCH_HOST={{ secrets.ELASTIC_SEARCH_HOST }} 

        
        # ibmcloud target -c ${{ secrets.ACCOUNT_ID }} -r ${{ secrets.REGION_NAME }} -g Default
        # ibmcloud ce project select --name ${{ secrets.CODE_ENGINE_PROJECT }} --quiet

        # ibmcloud ce application update --name "tourstravelserver" --registry-secret my-us-reg-secret \
        # --image "us.icr.io/${{ secrets.IBM_CR_NAMESPACE }}/${{ secrets.IMAGE_NAME }}:latest" \
        # --port 4000 \
        # --env REDIS_PASSWORD=${{secrets.REDIS_PASSWORD}} --env LOG_LEVEL=${{ secrets.LOG_LEVEL }} \ 
        # --image us.icr.io/${{ secrets.IBM_CR_NAMESPACE }}/elasticsearch:8.17.0 \
        # --env discovery.type=single-node \ 
        # --env xpack.security.enabled=false \
        # --port 9200 \
        # --image us.icr.io/${{ secrets.IBM_CR_NAMESPACE }}/kibana:8.17.0 \
        # --env ELASTICSEARCH_HOSTS=http://<elasticsearch-service-url>:9200 \
        # --port 5601 || \
        # ibmcloud ce application create --name "tourstravelserver" --registry-secret my-us-reg-secret \
        # --image "us.icr.io/${{ secrets.IBM_CR_NAMESPACE }}/${{ secrets.IMAGE_NAME }}:latest" \
        # --port 4000 \
        # --env REDIS_PASSWORD=${{secrets.REDIS_PASSWORD}} --env LOG_LEVEL=${{ secrets.LOG_LEVEL }} \
        # --image us.icr.io/${{ secrets.IBM_CR_NAMESPACE }}/kibana:8.17.0 \
        # --env discovery.type=single-node \ 
        # --env xpack.security.enabled=false \
        # --port 9200 \
        # --image us.icr.io/${{ secrets.IBM_CR_NAMESPACE }}/kibana:8.17.0 \
        # --env ELASTICSEARCH_HOSTS=http://<elasticsearch-service-url>:9200 \
        # --port 5601



        # ibmcloud ce application update --name "tourstravelserver" --registry-secret my-us-reg-secret \
        # --image "us.icr.io/${{ secrets.IBM_CR_NAMESPACE }}/${{ secrets.IMAGE_NAME }}:latest" --port 4000 \
        # --image "us.icr.io/${{ secrets.IBM_CR_NAMESPACE }}/${{ secrets.IMAGE_NAME_2 }}:latest" --port 6379 || \
        # ibmcloud ce application create --name "tourstravelserver" --registry-secret my-us-reg-secret \
        # --image "us.icr.io/${{ secrets.IBM_CR_NAMESPACE }}/${{ secrets.IMAGE_NAME }}:latest" --port 4000 \
        # --image "us.icr.io/${{ secrets.IBM_CR_NAMESPACE }}/${{ secrets.IMAGE_NAME_2 }}:latest" --port 6379
