name: Deploy to IBM Cloud Code Engine

on:
  push:
    branches:
      - main  # Change to your default branch name if necessary

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Log in to IBM Cloud
    - name: Log in to IBM Cloud
      run: |
        curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
        ibmcloud config --check-version=false
        ibmcloud login --apikey "${{ secrets.IBM_CLOUD_API_KEY }}" -r "${{ secrets.IBM_REGION }}"
    
    # install ibm dependencies
    - name: install ibm dependencies
      run: |
       ibmcloud plugin install container-registry
       ibmcloud plugin install code-engine


    # Log in to IBM Container Registry
    - name: Log in to IBM Container Registry
      run: |
        # ibmcloud cr login
        ibmcloud cr region-set us-south
        ibmcloud cr login --client docker
        ibmcloud cr namespace-add "${{ secrets.IBM_CR_NAMESPACE }}" || true

    # Build the container
    - name: Build and tag Docker image
      run: |
        docker build -t "icr.io/${{ secrets.IBM_CR_NAMESPACE }}/${{ secrets.IMAGE_NAME }}:latest" .
        # docker tag "icr.io/${{ secrets.IBM_CR_NAMESPACE }}/${{ secrets.IMAGE_NAME }}:latest" toursbackend:latest

      
    # Pull and push the official Redis image to ICR
    # If you prefer, you can skip pushing Redis to ICR and just reference the official image directly.
    - name: Prepare Redis Image
      run: |
        docker pull redis:latest
        docker tag redis:latest icr.io/${{ secrets.IBM_CR_NAMESPACE }}/${{ secrets.IMAGE_NAME_2 }}:latest
        # docker push us.icr.io/my-namespace/redis:latest
        

    #docker login to container registry
    - name: docker login to container registry
      run: |
         docker login -u iamapikey --password ${{ secrets.DOCKER_IAM }} icr.io

    # Push the node container to IBM Container Registry
    - name: Push node image to IBM Container Registry
      run: |
        docker push "icr.io/${{ secrets.IBM_CR_NAMESPACE }}/${{ secrets.IMAGE_NAME }}:latest"

    # Push the redis container to IBM Container Registry
    - name: Push redis image to IBM Container Registry
      run: |
        # docker push "icr.io/${{ secrets.IBM_CR_NAMESPACE }}/${{ secrets.IMAGE_NAME_ }}:latest"


    # Deploy to IBM Cloud Code Engine
    - name: Deploy to IBM Cloud Code Engine
      run: |
        # ibmcloud target -g Default  # Adjust resource group if needed
        ibmcloud ce project select --name "${{ secrets.CODE_ENGINE_PROJECT }}" --quiet

        ibmcloud ce application update --name "toursbackend" \
          --image "icr.io/${{ secrets.IBM_CR_NAMESPACE }}/${{ secrets.IMAGE_NAME }}:latest" \
          --image "icr.io/${{ secrets.IBM_CR_NAMESPACE }}/${{ secrets.IMAGE_NAME_2 }}:latest" || \
        ibmcloud ce application create --name "toursbackend" \
          --image "icr.io/${{ secrets.IBM_CR_NAMESPACE }}/${{ secrets.IMAGE_NAME }}:latest" \
          --image "icr.io/${{ secrets.IBM_CR_NAMESPACE }}/${{ secrets.IMAGE_NAME_2 }}:latest"
